Do not try to export binaries if --only-compilation-database is set
arduino/arduino-cli pull request #1181
Opened 2021-02-10 15:53 UTC by cmaglie

Otherwise an empty `build/fqbn/...` folder is created if `always-export-binaries` option is set via config file.

2021-02-10 16:00 UTC, silvanocerza requested changes
We need an integration test to verify this new behaviour, the rest looks good.

2021-02-11 07:18 UTC, ubidefeo approved these changes
Tested in the latest build and LS operations will not create the `build` folder.
Works fine

2021-02-11 14:28 UTC, silvanocerza approved these changes

2021-02-11 15:11 UTC, silvanocerza commented
Rebased to fix conflicts.

2021-02-11 16:17 UTC, merged