Add `--library` flag to `compile` command
arduino/arduino-cli pull request #1258
Opened 2021-04-08 10:38 UTC by silvanocerza

**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Adds a new flags to and existing command and related gRPC function.

- **What is the current behavior?**

There is currently no way of specifying a single custom library path when calling the `compile` command.

* **What is the new behavior?**

The user can now set the `--library` flag to specify one or more libraries root folder when compiling a sketch.

```
arduino-cli compile -b arduino:avr:uno --library=/path/to/lib /path/to/MySketch
arduino-cli compile -b arduino:avr:uno --library /path/to/lib1 --library /path/to/lib2 /path/to/MySketch
arduino-cli compile -b arduino:avr:uno --library=/path/to/lib1,/path/to/lib2 /path/to/MySketch
```

Libraries specified this way have top priority in case of conflict with identical libraries.

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Nope.

* **Other information**:

The docstring for the `--libraries` flag has also been modified to make it clearer and to differentiate it from this new `--library` flag.

The `--libraries` flag expects a path to a folder containing multiple libraries, much like the `<sketchbook>/libraries` folder does.
Assume we have two libraries in these paths:
```
/home/user/workspace/libraries/WiFi101
/home/user/workspace/libraries/AudioZero
```
The `--libraries` flag must be used like so:
```
arduino-cli compile -b arduino:avr:uno --libraries /home/user/workspace/libraries /path/to/MySketch
```

Instead the `--library` flag expects a path to the root folder of a single library, so it must be used like so:
```
arduino-cli compile -b arduino:avr:uno --library /home/user/workspace/libraries/WiFi101 --library /home/user/workspace/libraries/AudioZero /path/to/MySketch
```

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

2021-04-09 03:38 UTC, per1234 requested changes

2021-04-09 03:38 UTC, per1234 commented on legacy/builder/types/context.go
> +	LibrariesDirs        paths.PathList // List of paths pointing to individual libraries root folders
```suggestion
	LibraryDirs        paths.PathList // List of paths pointing to individual library root folders
```

2021-04-09 03:38 UTC, per1234 commented on legacy/builder/libraries_loader.go
> +	for _, dir := range ctx.LibrariesDirs {
```suggestion
	for _, dir := range ctx.LibraryDirs {
```

2021-04-09 03:38 UTC, per1234 commented on commands/compile/compile.go
> +	builderCtx.LibrariesDirs = paths.NewPathList(req.Library...)
```suggestion
	builderCtx.LibraryDirs = paths.NewPathList(req.Library...)
```

2021-04-09 08:15 UTC, silvanocerza commented on cli/compile/compile.go
> +		"List of custom libraries dir paths separated by commas. Or can be used multiple times for multiple libraries dir paths.")
I use them interchangeably, with this change I wanted to make it clear that `--libraries` must point to a single directory containing multiple libraries folders but am not sure I made it clearer.

I'm open to suggestions.

2021-04-13 09:46 UTC, ubidefeo approved these changes
Tested and working

2021-04-13 14:22 UTC, silvanocerza commented
@per1234 if it's ok for you I'll merge.

2021-04-13 14:47 UTC, per1234 approved these changes
Great work! I apologize for being so slow on the re-review.

2021-04-13 14:48 UTC, silvanocerza commented
@per1234 no worries. <3

2021-04-13 14:48 UTC, merged