[breaking] Refactor initialization steps
arduino/arduino-cli pull request #1274
Opened 2021-04-23 14:15 UTC by silvanocerza

**Please check if the PR fulfills these requirements**

- [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [ ] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

A big refactoring of the initialization steps run by the CLI both when run "one shot" or in daemon mode.

- **What is the current behavior?**

TODO

* **What is the new behavior?**

TODO

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Yes.
TODO

* **Other information**:

TODO

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

2021-04-27 07:40 UTC, per1234 requested changes

2021-04-27 10:24 UTC, cmaglie commented on commands/core/install.go
> +	_, status := commands.Init(&rpc.InitRequest{Instance: &rpc.Instance{Id: req.Instance.Id}})
This may be changed to:
```suggestion
	_, status := commands.Init(&rpc.InitRequest{Instance: req.Instance})
```

2021-05-07 09:05 UTC, silvanocerza commented
Rebased after #1278 merge.

2021-06-15 14:47 UTC, cmaglie approved these changes

2021-06-16 15:30 UTC, merged