Refactored `board details` to use pluggable discovery
arduino/arduino-cli pull request #1332
Opened 2021-06-23 14:05 UTC by cmaglie

Now `board details` return the identification properties got from `upload_port` properties.

Before:
```
$ arduino-cli board details arduino:samd:mkr1000 | grep Ident -C1

Identification properties: VID:0x2341 PID:0x804e                                                     
                           VID:0x2341 PID:0x004e                                                     
$ arduino-cli board details arduino:samd:mkr1000 --format json|jq .identification_prefs
[
  {
    "usb_id": {
      "vid": "0x2341",
      "pid": "0x804e"
    }
  },
  {
    "usb_id": {
      "vid": "0x2341",
      "pid": "0x004e"
    }
  },
  {
    "usb_id": {
      "vid": "0x2341",
      "pid": "0x824e"
    }
  },
  {
    "usb_id": {
      "vid": "0x2341",
      "pid": "0x024e"
    }
  }
]
```

After:
```
$ arduino-cli board details arduino:samd:mkr1000 | grep Ident -C1

Identification properties: vid=0x2341                                                             
                           pid=0x804e                                                             

Identification properties: vid=0x2341                                                             
                           pid=0x004e                                                             

Identification properties: vid=0x2341                                                             
                           pid=0x824e                                                             

Identification properties: vid=0x2341                                                             
                           pid=0x024e                       
$ arduino-cli board details arduino:samd:mkr1000 --format json | jq .identification_properties
[
  {
    "properties": {
      "pid": "0x804e",
      "vid": "0x2341"
    }
  },
  {
    "properties": {
      "pid": "0x004e",
      "vid": "0x2341"
    }
  },
  {
    "properties": {
      "pid": "0x824e",
      "vid": "0x2341"
    }
  },
  {
    "properties": {
      "pid": "0x024e",
      "vid": "0x2341"
    }
  }
]
```

2021-06-28 13:08 UTC, silvanocerza approved these changes

2021-07-05 08:58 UTC, per1234 requested changes

2021-07-05 08:58 UTC, per1234 commented on arduino/cores/board.go
> +// GetIdentificationProperties calculate and returns a list of properties sets
```suggestion
// GetIdentificationProperties calculates and returns a list of properties sets
```

2021-07-05 08:58 UTC, per1234 commented on docs/UPGRADING.md
> +now the properties have been renamed from `identification_prefs` to `identification_properties` and they are no more
```suggestion
now the properties have been renamed from `identification_prefs` to `identification_properties` and they are no longer
```

2021-07-22 15:47 UTC, merged