Improve json decoding
arduino/arduino-cli pull request #1402
Opened 2021-08-19 14:11 UTC by cmaglie

I found that the standard golang JSON decoder is very slow. This is particularly noticeable because the library_index.json is constantly growing (currently we are at ~20Mb) and the parsing time adds up at every invocation of the cli.

This PR:
- use `easyjson` library for parsing the library_index.json
- updates the testdata/library_index.json with the latest current
- add a benchmark to test JSON decoding performances

Here the result:
```
$ go test -v -benchmem -bench BenchmarkIndexParsing github.com/arduino/arduino-cli/arduino/libraries/librariesindex
=== RUN   TestIndexer
--- PASS: TestIndexer (0.16s)
goos: linux
goarch: amd64
pkg: github.com/arduino/arduino-cli/arduino/libraries/librariesindex
cpu: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
BenchmarkIndexParsingStdJSON
BenchmarkIndexParsingStdJSON-8                 5         214872730 ns/op          94.52 MB/s    58956539 B/op     418973 allocs/op
BenchmarkIndexParsingEasyJSON
BenchmarkIndexParsingEasyJSON-8               16          69215472 ns/op         293.42 MB/s    56162664 B/op     418966 allocs/op
PASS
ok      github.com/arduino/arduino-cli/arduino/libraries/librariesindex 4.442s
```

2022-05-05 09:29 UTC, ubidefeo approved these changes
I have run the build from this PR for about one hour on several projects and have not been able to break it.
From a usage point of view it LGTM

2022-05-05 11:38 UTC, per1234 requested changes

2022-05-05 11:38 UTC, per1234 commented on .github/workflows/check-easyjson.yml
> +      - "codecov.ya?ml"
```suggestion
      - "go.mod"
      - "go.sum"
      - "Taskfile.ya?ml"
      - "**.go"
  pull_request:
    paths:
      - ".github/workflows/check-easyjson.ya?ml"
```
As far as I can tell, it should not be necessary to trigger the workflow on a change to the Codecov configuration file.

2022-05-05 12:23 UTC, per1234 approved these changes

2022-05-05 12:51 UTC, umbynos approved these changes

2022-05-05 13:07 UTC, merged

2022-05-06 08:23 UTC, cmaglie commented
For the record: we are using a patched version of `easyjson` until this patch is accepted upstream: https://github.com/mailru/easyjson/pull/372