Bump go version we use to build and release to go 1.17.3
arduino/arduino-cli pull request #1567
Opened 2021-11-24 10:14 UTC by umbynos

**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Update go version in the release pipeline
- **What is the current behavior?**

We currently use go 1.16.4 to build
* **What is the new behavior?**

We currently use go 1.17.3 to build
- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

nope
* **Other information**:

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

2021-11-24 10:15 UTC, umbynos commented
I have run the tests locally and it seems there are no regressions with go 1.17

2021-11-24 15:25 UTC, rsora commented
Let's be cautious on this one, I'll wait for other tasks to be closed, and also to dig a bit more with testing :mag_right:

2021-11-24 16:00 UTC, umbynos commented
BTW @silvanocerza finished running local tests on macOS and everything went smooth

2021-11-25 10:10 UTC, umbynos commented
Note for future self: The homebrew  version is built with go 1.17 (and not pinned) since 0.20.0 https://github.com/Homebrew/homebrew-core/pull/89858

2021-11-26 08:57 UTC, silvanocerza approved these changes

2021-11-26 08:58 UTC, silvanocerza commented
@rsora @umbynos I think we can merge this, I have been building the `arduino-cli` with Go 1.17 since it came out and never had any issue connected to it.

2022-03-14 09:06 UTC, per1234 requested changes

2022-03-14 09:06 UTC, per1234 commented on DistTasks.yml
> +  GO_VERSION: "1.17.3"
```suggestion
  GO_VERSION: "1.17.8"
```
This is the current latest available:
https://github.com/elastic/golang-crossbuild/releases/tag/1.17.8

Unless there is a specific reason for using 1.17.3, I suggest we get all the way up to date while we are at it.

2022-03-14 10:51 UTC, per1234 requested changes
These should also be updated to say 1.17:

- https://github.com/arduino/arduino-cli/blob/master/docs/CONTRIBUTING.md#prerequisites
- https://github.com/arduino/arduino-cli/blob/master/docs/CONTRIBUTING.md#local-development

(they were forgotten during the Go 1.14 -> 1.16 transition)

2022-03-14 11:01 UTC, per1234 approved these changes

2022-03-14 11:20 UTC, merged