Add board autodetection on upload
arduino/arduino-cli pull request #1581
Opened 2021-12-02 17:28 UTC by silvanocerza

**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**

Adds a new feature.

- **What is the current behavior?**

The user must always provide an FQBN when trying to upload either with the `compile` or `upload` commands.

Example: 
* `arduino-cli upload -p /dev/ttyACM1 -b arduino:avr:uno`
* `arduino-cli compile -u -p /dev/ttyACM1 -b arduino:avr:uno`

* **What is the new behavior?**

The user can now upload to a port without specifying an FQBN, if there is no ambiguity in the list of detected boards by the discoveries the commands will be successful. If the `arduino-cli` can't understand with 100% certainty which board is connected to the specified port the commands will exit with an error and let the user know that an FQBN must be provided.

Example commands:

* `arduino-cli upload -p /dev/ttyACM1`
* `arduino-cli compile -u -p /dev/ttyACM1`

This also affects the gRPC consumers.

- **Does this PR introduce a breaking change, and is
[titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**

Nope.

* **Other information**:

New fields have been added to existing gRPC messages so consumers will need to regenerate the source files from the `.proto` but there is no breaking change.

Closes #1357.

---

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

2021-12-03 14:47 UTC, umbynos requested changes
Also if you try to compile without uploading (`-u`) and without specifying the fqbn the cli returns an errror message different than before:
`Error during FQBN detection: Missing port protocol` new
`Error during build: Missing FQBN (Fully Qualified Board Name)` old

2021-12-03 14:47 UTC, umbynos commented on cli/compile/compile.go
> +		sk = arguments.NewSketch(sketchPath)
Is it necessary to use `NewSketch` even if detected board is not defined?

2021-12-06 10:08 UTC, umbynos approved these changes

2021-12-07 08:56 UTC, merged

2022-02-08 09:53 UTC, ubidefeo commented
@silvanocerza @umbynos 
this doesn't work for me

I have a Nano 33 IoT attached to my machine.
It is successfully discovered by `arduino-cli board list` but when running
```shell
$> arduino-cli compile -u -p /dev/cu.usbmodem101
Error during FQBN detection: Missing FQBN (Fully Qualified Board Name)
```