Add env variable to let tools know if the cli is running as a grpc daemon or not
arduino/arduino-cli pull request #1640
Opened 2022-01-26 15:52 UTC by cmaglie

**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

**What kind of change does this PR introduce?**
Adds a new environment variable `ARDUINO_MODE` that is passed on all tools launched by the CLI.
The value of the variable may be:
* `cli` if the `arduino-cli` is used from terminal or scripts as a pure command-line tool.
* `daemon` if the `arduino-cli` is launched as a daemon.

**Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**
No breaking changes

2022-01-26 16:22 UTC, per1234 requested changes
I know this is still WIP, but I want to add a "to do" that the final proposal should include documentation. Otherwise it will end up as one of those esoteric features nobody remembers a year from now.

It isn't clear to me which is the ideal place to document this. The available options are probably:

- [`arduino-cli daemon` command docs](https://arduino.github.io/arduino-cli/dev/commands/arduino-cli_daemon/#synopsis)
- [Platform Specification](https://arduino.github.io/arduino-cli/dev/platform-specification)

Any opinions on the location?

2022-01-26 17:08 UTC, cmaglie commented
IMHO https://arduino.github.io/arduino-cli/dev/platform-specification/#tools is the best place, I'll write down some notes there.

2022-01-28 11:40 UTC, cmaglie commented
@PaulStoffregen
After a brief internal discussion, I've changed the env variable to `ARDUINO_USER_AGENT` (more detailed description in the opening post of this PR: https://github.com/arduino/arduino-cli/pull/1640#issue-1115178636).

The rationale is that the previous `ARDUINO_MODE=cli/daemon` does not contain enough information to determine if the process is running on a GUI, there are some corner cases like:
- running the gRPC daemon as a backend for an HTTP service endpoint: in this case we don't want to display a GUI in a headless server
- other software that uses the CLI daemon that does not necessarily have a GUI
- in general, running the `daemon` does not imply running a GUI
 
I guess you would like to check if the user agent contains the string `ArduinoIDE` to actually display a GUI.

2022-01-28 12:06 UTC, per1234 requested changes
Please also document the breaking changes to the public Go package API according to the standard policy:
https://arduino.github.io/arduino-cli/dev/CONTRIBUTING/#breaking

2022-01-28 14:18 UTC, per1234 approved these changes
Thanks Cristian!

2022-01-28 15:40 UTC, silvanocerza commented on executils/process.go
> +	p.cmd.Env = append(p.cmd.Env, values...)
```suggestion
	p.cmd.Env = os.Environ()
	p.cmd.Env = append(p.cmd.Env, values...)
```

2022-01-31 14:26 UTC, silvanocerza approved these changes

2022-01-31 14:27 UTC, merged

2022-01-31 21:00 UTC, PaulStoffregen commented
Thanks!!

Today I'm still working on porting my pluggable serial monitor code to Windows.  Hoping I can wrap that up tonight, and then tomorrow start using the next nightly build with this environment variable.

2022-01-31 21:18 UTC, cmaglie commented
Do not rush on this one, we need to fix also the Arduino IDE to fully support it https://github.com/arduino/arduino-ide/issues/790