Fixed '--libraries' and '--library' flags description in compile command
arduino/arduino-cli pull request #1732
Opened 2022-05-12 15:09 UTC by cmaglie

**Please check if the PR fulfills these requirements**

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

**What kind of change does this PR introduce?**
Fixed '--libraries' and '--library' flags description in compile command

**What is the current behavior?**
the description obtained from `arduino-cli compile -h` is:
```
      --libraries strings            List of custom libraries dir paths separated by commas. Or can be used multiple times for multiple libraries dir paths.
      --library strings              List of paths to libraries root folders. Libraries set this way have top priority in case of conflicts. Can be used multiple times for different libraries.
```

and is wrong (well, at least is not very clear...)

* **What is the new behavior?**
```
      --libraries strings            Path to a collection of libraries. Contained libraries override the ones found in the default libraries folder. Can be used multiple times or entries can be comma separated.
      --library strings              Path to a single library’s root folder. Overrides other occurrences of the library found in default libraries folder or passed in via --libraries. Can be used multiple times or entries can be comma separated.
```

**Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**
No

2022-05-12 15:52 UTC, per1234 reviewed
I'm wondering whether it is wise to attempt an explanation of library priority here. Location is [only one of the factors](https://arduino.github.io/arduino-cli/dev/sketch-build-process/#location-priority).

2022-05-20 15:35 UTC, per1234 requested changes
I may not have communicated clearly. I was not suggesting that we should add to it. I was suggesting that we remove the incomplete information about library priority.

2022-05-20 15:35 UTC, per1234 commented on cli/compile/compile.go
> +		tr("Path to a single library’s root folder. Overrides other occurrences of the library found in default libraries folder or passed in via --libraries. Can be used multiple times or entries can be c
```suggestion
		tr("Path to a single library’s root folder. Can be used multiple times or entries can be comma separated."))
```

2022-05-20 15:35 UTC, per1234 commented on cli/compile/compile.go
> +		tr("Path to a collection of libraries. Contained libraries override the ones found in the default libraries folder. Can be used multiple times or entries can be comma separated."))
```suggestion
		tr("Path to a collection of libraries. Can be used multiple times or entries can be comma separated."))
```

2022-05-24 12:41 UTC, cmaglie commented
That makes sense. I've also changed the description of the gRPC API.

2022-05-24 13:12 UTC, merged