[breaking] Refactor `DownloadProgress` gRPC message: more clear field meaning.
arduino/arduino-cli pull request #1875
Opened 2022-09-13 14:03 UTC by cmaglie

**Please check if the PR fulfills these requirements**

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [X] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

* **What kind of change does this PR introduce?**
Refactor the `DownloadProgress` messages.

- **What is the current behavior?**
It's not very clear how the fields in the progress reports are populated.

* **What is the new behavior?**
The new message structure should be much more clearer.

- **Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?**
Yes

2022-09-23 10:52 UTC, umbynos approved these changes

2022-10-02 13:23 UTC, per1234 requested changes

2022-10-04 14:02 UTC, per1234 approved these changes

2022-10-05 08:30 UTC, kittaakos commented
@cmaglie, could you please merge this PR if it's ready? Thank you!

2022-10-05 08:38 UTC, merged