Store all temporary files under a single folder
arduino/arduino-cli pull request #2031
Opened 2023-01-07 18:10 UTC by giulianopz

Fix #2028

Any temporary file will be persisted in a new dedicated folder named as "arduino" located in the OS-specific temporary directory, e.g.: 
```
/tmp/
├── arduino
│   ├── arduino-core-cache
│   │   └── core_arduino_avr_uno_640aa5b4d646262327bbea65c3462b39.a 
│   └── arduino-sketch-89E1544CF5F196B29E530BA6940B661F
│       ├── 06.ino.elf
│       ├── 06.ino.with_bootloader.bin
│       ├── build.options.json
│       ├── compile_commands.json
│       ├── core
│       │   ├── abi.cpp.d
[...]
```

This change is meant to make easier maintenance operations for both end-users and operating-systems.

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?

All code lines which reference the default tmp dir to store temporary files were changed to prefix "arduino-core-cache" and "arduino-sketch-<MD5>" with "arduino/" as their parent.

## What is the current behavior?

See issue #2028.

## What is the new behavior?

All the temporary files will be put inside a new "arduino" folder in the default temporary directory of the OS.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

Not sure if this is a braking change with respect to older versions of the cli.

2023-01-07 18:16 UTC, pzygielo commented
Will it work in multi-user environment for the second and next users, once the first temporary `arduino` directory is created?

2023-01-07 20:54 UTC, giulianopz commented
> Will it work in multi-user environment for the second and next users, once the first temporary `arduino` directory is created?

The second user (and next ones) will not be allowed to compile the same sketch the first user built. But only if they can access the exact same sketch folder: the name of the tmp dir of a sketch ends with an MD5 hash value generated from the path of such dir.

This happens also with the current version of the cli, anyway.  

This PR just deals with grouping the two main dirs containing tmp files as requested in the referenced issue. You should open a new issue, I guess, if you think that this kind of collisions can really happen (I don't know, to be honest).

2023-01-07 23:20 UTC, pzygielo commented
> This happens also with the current version of the cli (doesn't it?), anyway.

Now that you shown it I can see that `arduino-core-cache` locks other users already indeed.

2023-01-09 14:04 UTC, Bikappa requested changes

2023-01-09 14:04 UTC, Bikappa commented on arduino/sketch/sketch.go
> +	return paths.TempDir().Join("arduino/arduino-sketch-" + md5Sum)
To allow cross platform compatibility in regards of the path separation, please use
```suggestion
	return paths.TempDir().Join("arduino", "sketch-" + md5Sum)
```
Also let's simplify the path a bit, by removing the double "arduino"

2023-01-10 12:08 UTC, Bikappa submitted a review, later dismissed

2023-01-10 13:19 UTC, Bikappa approved these changes

2023-01-10 13:21 UTC, merged