[skip-changelog] Add query parameters to urls generated by lib commands
arduino/arduino-cli pull request #2034
Opened 2023-01-17 09:10 UTC by MatteoPologruto

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)

## What kind of change does this PR introduce?
Code enhancement

## What is the new behavior?
Three different query parameters have been added to the urls generated by `lib` commands like `lib install` and `lib upgrade`. The query parameters are:
- `install`: which is selected when a library is installed through `lib install`;
- `upgrade`: which is selected when a library is upgraded through `lib upgrade`;
- `depends`: which is selected when a library dependency is installed.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?
No

2023-01-17 11:59 UTC, umbynos requested changes
left some suggestions

2023-01-17 11:59 UTC, umbynos commented on arduino/httpclient/httpclient.go
>  // A DownloadProgressCB callback function must be passed to monitor download progress.
Could you please change this comment and include info regarding the new parameter?

2023-01-17 11:59 UTC, umbynos commented on arduino/resources/download.go
>  // Messages are passed back to the DownloadProgressCB using label as text for the File field.
same as above

2023-01-17 11:59 UTC, umbynos commented on commands/lib/download.go
>  // LibraryDownload FIXMEDOC
This could be the chance to fix this

2023-01-17 11:59 UTC, umbynos commented on commands/lib/install.go
>  // LibraryInstall FIXMEDOC
same as above

2023-01-17 11:59 UTC, umbynos commented on commands/lib/install.go
> +		if libRelease.GetName() == req.Name {
why is this requires? It's not so clear

2023-01-17 11:59 UTC, umbynos commented on internal/cli/lib/download.go
> +		_, err := lib.LibraryDownload(context.Background(), libraryDownloadRequest, feedback.ProgressBar(), "")
I don't know if this has to be left empty

2023-01-17 14:10 UTC, umbynos approved these changes
LGTM :checkered_flag:

2023-01-17 15:06 UTC, merged

2023-01-18 08:37 UTC, cmaglie commented
I see a couple of problems with this PR:
* it changes the signature of the function `commands.LibraryDownload`, this is a breaking change that is not documented
* all public functions in package `commands` are made to strictly follow the gRPC API. If we need to add a parameter in any of the public functions of `command.*` we must first change the gRPC API and rebuild it otherwise, we allow the CLI to bypass the gRPC API. In fact, this implementation works only in the CLI, there is no way to access this feature from the gRPC API (so it will not work in the Arduino IDE or any other gRPC client).