Use the correct library when a relative path is passed as `--library` value
arduino/arduino-cli pull request #2126
Opened 2023-03-27 15:32 UTC by MatteoPologruto

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?
Code imperfection fix

## What is the current behavior?
Compiling an example of a manually downloaded library fails if  the command is executed inside the examples directory and a relative path to the library itself is specified.
```
C:\Users\m.pologruto>arduino-cli lib uninstall ArduinoIoTCloud
Uninstalling [ArduinoIoTCloud@1.11.0]...

C:\Users\m.pologruto>cd Downloads/ArduinoIoTCloud-1.11.0/examples/ArduinoIoTCloud-Basic

C:\Users\m.pologruto\Downloads\ArduinoIoTCloud-1.11.0\examples\ArduinoIoTCloud-Basic>arduino-cli compile -b arduino:samd:nano_33_iot --library ../../
...
...
Error during build: CreateFile ..\..\..\src\ArduinoIoTCloud.cpp: The system cannot find the path specified.
```
If the same library is installed with `lib install`, the library is picked from the Sketchbook's libraries directory.

## What is the new behavior?
If the relative path to a library is correct, that library will be chosen over other instances of it.

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?
No

2023-03-28 04:30 UTC, per1234 requested changes
There is no need to bundle the entire ArduinoIoTCloud library as test data. You can use a minimal library instead:

[FooLib.zip](https://github.com/arduino/arduino-cli/files/11085270/FooLib.zip)

The only requirement for the test data:

- A sketch that contains an `#include` directive.
- A library that:
  - contains a header file with name matching the `#include` directive in the sketch
  - contains at least one source file (e.g., `FooLib.cpp`)

2023-03-28 11:36 UTC, per1234 requested changes

2023-03-28 11:36 UTC, per1234 commented on internal/integrationtest/compile_3/compile_test.go
> +
```suggestion
```

This code doesn't serve any purpose that I can see

2023-03-28 12:21 UTC, cmaglie requested changes

2023-03-28 12:21 UTC, cmaglie commented on commands/compile/compile.go
> +	}
Move this change from `commands` package (gRPC), to `internal/cli` package (arduino-cli).

It doesn't make much sense to use relative paths in a gRPC call as a daemon. It makes sense in the `arduino-cli` as a command line, so the paths must be absolutized before entering the gRPC request.

2023-03-29 05:47 UTC, per1234 approved these changes
Thanks Matteo!

2023-03-29 09:44 UTC, cmaglie approved these changes

2023-03-29 10:22 UTC, merged