Report compiler errors in machine readable format
arduino/arduino-cli pull request #2182
Opened 2023-05-19 17:34 UTC by cmaglie

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [X] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [X] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

Adds parsing of the compiler errors and warning to present them in a machine-readable way if JSON output is selected or if the `Compile` gRPC call is used.

## What is the current behavior?

The compiler output is presented as a big blob of text.

## What is the new behavior?

The compiler output is dissected into a structured format so clients can easily consume it.

```
$ arduino-cli compile -u -b arduino:avr:leonardo ~/Arduino/Blink/ -v --format json |jq .builder_result.diagnostics
[
  {
    "column": 16,
    "context": [
      {
        "file": "/home/megabug/Workspace/sketchbook-cores-beta/libraries/Audio/src/Audio.h",
        "line": 16,
        "message": "included from here"
      },
      {
        "file": "/home/megabug/Arduino/Blink/Blink.ino",
        "line": 1,
        "message": "included from here"
      }
    ],
    "file": "/home/megabug/Workspace/sketchbook-cores-beta/libraries/Audio/src/DAC.h",
    "line": 21,
    "message": "expected ')' before '*' token\n  DACClass(Dacc *_dac, uint32_t _dacId, IRQn_Type _isrId) :\n                ^",
    "severity": "ERROR"
  },
  {
    "column": 2,
    "context": [
      {
        "file": "/home/megabug/Workspace/sketchbook-cores-beta/libraries/Audio/src/Audio.h",
        "line": 16,
        "message": "included from here"
      },
      {
        "file": "/home/megabug/Arduino/Blink/Blink.ino",
        "line": 1,
        "message": "included from here"
      }
    ],
    "file": "/home/megabug/Workspace/sketchbook-cores-beta/libraries/Audio/src/DAC.h",
    "line": 35,
    "message": "'Dacc' does not name a type\n  Dacc *dac;\n  ^~~~",
    "severity": "ERROR"
  },
  ...
```

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

No

## Other information

Fix https://github.com/arduino/arduino-cli/issues/1121

2023-05-25 09:31 UTC, cmaglie commented
TODO: test this with more compilers...

2023-05-26 09:56 UTC, alessio-perugini submitted a review, later dismissed
LGTM. The only think that I'm concerned about is that starting from now on this is something new that we need to maintain so here are some ideas for future PRs:
- Add more tests for different versions of compilers we're using.
- Adding fuzz testing in the parser might be helpful?

2023-05-26 09:56 UTC, alessio-perugini commented on internal/builder/diagnostics/compiler_detection.go
> +// If probleCompiler is true, the compiler may be executed with different flags to
```suggestion
// If probeCompiler is true, the compiler may be executed with different flags to
```
typo

2023-05-26 09:56 UTC, alessio-perugini commented on internal/builder/diagnostics/parser_test.go
> +	// fmt.Println(string(output))
```suggestion
```
I guess some debbugging leftovers :nerd_face:

2023-09-21 09:41 UTC, cmaglie commented
> Add more tests for different versions of compilers we're using.

This will surely help. Adding a test is a tedious process tho...

> Adding fuzz testing in the parser might be helpful?

Interesting, BTW I think that the fuzzer may not help to improve the parsing correctness because:
* we have no way to check if the input produced by the fuzzer is a plausible gcc output
* we have no way to check if the parser output is correct against the given fuzzer input

Anyway, it may help to test the parser's resistance to crazy inputs...

2023-11-08 10:29 UTC, alessio-perugini requested changes
I'd like to have an integration test that checks for the new `diagnostic` field.
If you want you can either:
- Expand the already existing integration test `internal/integrationtest/compile_3/compile_test.go|102 col 6| func TestCompilerErrOutput(t *testing.T) {` 
- Create a new one

Example:
```go
TestCompilerErrOutput(t *testing.T) {
	...
	// prepare sketch
	sketch, err := paths.New("testdata", "blink_with_wrong_cpp").Abs()
	require.NoError(t, err)

	// Run compile and catch err stream
	out, _, err := cli.Run("compile", "-b", "arduino:avr:uno", "--format", "json", sketch.String())
	...
	requirejson.Query(t, out, `.diagnostics | length > 0`, `true`)
```

2023-11-08 13:47 UTC, alessio-perugini approved these changes

2023-11-08 16:26 UTC, alessio-perugini approved these changes

2023-11-08 16:31 UTC, merged