feature: Added raw terminal support in `montior` command
arduino/arduino-cli pull request #2291
Opened 2023-09-01 16:02 UTC by cmaglie

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [x] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [x] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?

Adds the `--raw` flag to the `monitor` command to put the terminal in raw mode.
When the terminal is in raw mode:
* Control chars are not processed
* Terminal is not line-buffered anymore (each char is sent as soon as the key is pressed)
* Sent chars are not echoed
* CR are not automatically added after NL
This may result in weird behavior but it may be the desired result, for example, see #2251

## What is the current behavior?

## What is the new behavior?

```
$ cat Term.ino 
void setup() {
	Serial.begin(9600);
}

void loop() {
	while (Serial.available() > 0) {
		char c = Serial.read(); 

		if (c < 0x10) Serial.print("0");
		Serial.print(c, HEX);
		Serial.print(" ");

		if (c=='\r') Serial.println();
	}
	delay(10);
}
$ arduino-cli monitor -p /dev/ttyACM0 --config baudrate=9600 --raw
Monitor port settings:
baudrate=9600
Connected to /dev/ttyACM0! Press CTRL-C to exit.
6A 77 69 65 71 77 68 75 64 69 73 61 73 64 71 77 65 0D <----- data is printed as soon as they are typed
0D                                                    <----- key pressed are not echoed back
0D 
73 6A 64 68 6A 73 64 68 71 6A 77 65 0D 
$ 
```

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?

No

## Other information

I've tested it on Linux only. More testing is needed especially on Windows.

Fix #2251

2023-09-04 08:02 UTC, alessio-perugini requested changes
I've tested on:
Linux - ubuntu: :heavy_check_mark: 
Windows 11: :heavy_check_mark:

2023-09-06 08:02 UTC, alessio-perugini approved these changes

2023-09-06 08:53 UTC, merged

2024-01-17 08:39 UTC, oscherler commented
You mention that in raw mode, “CR are not automatically added after NL.” This confuses me on two levels:

1. Usually, CR appears before LF;
2. This sentence seems to imply that in normal mode, CR is added to new lines, but on my Mac, only LF is sent on new line (causing my old projects to break with arduino-cli.)

2024-02-02 15:37 UTC, cmaglie commented
> Usually, CR appears before LF;

You're right, the sequence is CR+LF, I've edited the post.

> This sentence seems to imply that in normal mode, CR is added to new lines, but on my Mac, only LF is sent on new line (causing my old projects to break with arduino-cli.)

In raw mode, the OS terminal emulation is bypassed, and when you press the "Enter" key, the CLI gets directly the `0x0D` char code and sends it to the serial port without further processing.

In non-raw mode, the terminal emulator does some processing before the character reaches `arduino-cli`, on my Linux box "Enter" is translated into a CR+LF sequence (my Linux terminal emulation is `xterm-256color` it may be different on other OS).