[skip-changelog] Improve the definition of FQBN and explicitly state which characters are allowed
arduino/arduino-cli pull request #2509
Opened 2024-01-18 16:25 UTC by MatteoPologruto

## Please check if the PR fulfills these requirements

See [how to contribute](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/)

- [ ] The PR has no duplicates (please search among the [Pull Requests](https://github.com/arduino/arduino-cli/pulls)
      before creating one)
- [ ] The PR follows
      [our contributing guidelines](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#pull-requests)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] `UPGRADING.md` has been updated with a migration guide (for breaking changes)
- [ ] `configuration.schema.json` updated if new parameters are added.

## What kind of change does this PR introduce?
Documentation enhancement

## What is the new behavior?
No changes

## Does this PR introduce a breaking change, and is [titled accordingly](https://arduino.github.io/arduino-cli/latest/CONTRIBUTING/#breaking)?
No

## Other information

2024-01-22 10:00 UTC, alessio-perugini requested changes
I remember that talking with @cmaglie we wanted to enforce this check in the codebase. 
Let's wait for his response if we want to tackle that in the same PR.

2024-01-25 12:44 UTC, cmaglie requested changes

2024-01-25 12:44 UTC, cmaglie commented on docs/FAQ.md
> +- `arduino::uno`, `:avr:uno`, `::uno`
I don't understand this piece, AFAIK the mandatory part is the triple `VENDOR:ARCHITECTURE:BOARD_ID` (not just `BOARD_ID`).
The formula above is correct IMHO:
```
VENDOR:ARCHITECTURE:BOARD_ID[:MENU_ID=OPTION_ID[,MENU2_ID=OPTION_ID ...]]
```
from here we can deduce that the optional part is the MENU_ID=OPTION_ID.
Also, the OPTION_ID must match one of the possible value for the corresponding MENU_ID, it cannot be omitted:

```
$ arduino-cli board details -b arduino:avr:mega:cpu=
Error getting board details: Unknown FQBN: getting build properties for board arduino:avr:mega: invalid value '' for option 'cpu'
$ arduino-cli board details -b arduino:avr:mega:cpu
Error getting board details: Invalid FQBN: invalid config option: cpu
$ arduino-cli board details -b arduino:avr:mega:cpu=atmega2560
[...correct output is displayed...]
```

IMHO we should remove the `## What fields of the FQBN are optional?` section entirely.

2024-01-25 12:48 UTC, cmaglie commented
> I remember that talking with @cmaglie we wanted to enforce this check in the codebase. Let's wait for his response if we want to tackle that in the same PR.

Yep, it would be nice to start enforcing it.
I don't know how much platforms would break, BTW it seems very unlikely (in case we may relax the specification to include some extra char later).

2024-02-05 09:30 UTC, cmaglie approved these changes

2024-02-06 08:32 UTC, alessio-perugini approved these changes

2024-02-06 08:33 UTC, merged

2024-02-10 10:46 UTC, dankeboy36 commented
Thanks for the feature. I see `arduin-o:av-r:un-o:a=b=c=d` is valid. What config option and value does it imply? Can you confirm that config option `a` has a value of `"b=c=d"`?

2024-02-12 08:49 UTC, MatteoPologruto commented
Hello @dankeboy36! Yes, I am confirming that `arduin-o:av-r:un-o:a=b=c=d` is a valid FQBN and the config key `a` has the value of `b=c=d`.